### ISSUE TITLE
Can the classified results be automatically classified and exported to the corresponding folder?

### ISSUE THREAD

**Issue by heytony965342** [chenwr727/Smart-Album#12]
Can the classified results be automatically classified and exported to the corresponding folder?

**Comment by chenwr727** [comment]
Sure, but I haven't done this work. You can retrieve all the classification results by querying the database (_sql_app.db_). You can refer to _modules/crud.py_ for operations, such as using _get_picture_face_by_label_id_ to get the corresponding picture_id based on the label_id, and then proceed with the export.
